name = "cherrybot"
compatibility_date = "2025-07-07"

# Configure as a static site
workers_dev = true
main = "./workers-site/index.js"

[site]
bucket = "./cherrybot"

[build]
command = ""
upload.format = "directory"

[assets]
directory = "./cherrybot"
